# Generated by Django 5.2.1 on 2025-05-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaservicio',
            options={'verbose_name': 'Categoría Servicio', 'verbose_name_plural': 'Categorías Servicio'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
